# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=26.1.2
	yarn_mappings=26.1.2+build.1
	loader_version=0.18.2

# Mod Properties
	mod_version = 2.2.1
	maven_group = derp
	archives_base_name = squake

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_api_version=0.149.0+26.1.2
	modmenu_version=18.0.0-beta.1
	cloth_config_version=26.1.154
